mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
	    url(r'^polls/', include('polls.urls')),
	    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name='polls'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	#url(r'^home/$', views.IndexView.as_view(), name='home'),
	url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
	url(r'^(?P<pk>[0-9]+)/results/$',views.ResultsView.as_view(),name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
	#url(r'^home/$',views.home,name='home'),
	url(r'^station/$',views.station,name='station'),
	

]

polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.utils.encoding import python_2_unicode_compatible
#from django.utils import timezone
from datetime import timedelta, datetime
from django.utils.timezone import make_aware

@python_2_unicode_compatible
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

@python_2_unicode_compatible
class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete = models.CASCADE)
	choice_text= models.CharField(max_length=200)
	votes= models.IntegerField(default=0)

	def __str__(self):
			return self.choice_text

class Forecast(models.Model):

	timestamp = models.DateTimeField()
	temperature = models.DecimalField(max_digits=12, decimal_places=2)
	description = models.CharField(max_length=150)
	city = models.CharField(max_length=150)

	def __str__(self):
		return self.temperature

	def save(self, *args, **kwargs):
		if not self.id:
			naive_datetime = datetime.now()
			aware_datetime = make_aware(naive_datetime)
			self.timestamp = aware_datetime
		return super(Forecast, self).save(*args, **kwargs)
		

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404 , render

# Create your views here.

import time
import decimal
from datetime import datetime
import logging

from django.http import HttpResponse,HttpResponseRedirect, JsonResponse
from django.template import loader
from .models import Choice, Question, Forecast
from django.urls import reverse
from django.views import generic
from django.views.generic import TemplateView
#from django.utils import timezone
import Adafruit_BBIO.GPIO as GPIO
from time import sleep
from SprinklerLord.Station import Station

from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView

from apscheduler.schedulers.background import BackgroundScheduler
from django_apscheduler.jobstores import DjangoJobStore, register_events, register_job



logging.basicConfig(filename='sprinklerLog.log',format='%(asctime)s %(levelname)-8s %(message)s', level=logging.INFO,datefmt='%Y-%m-%d %H:%M:%S')

class IndexView(TemplateView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'


	def get_queryset(self):
		return Question.objects.filter(pub_date__lte = timezone.now()).order_by('-pub_date')[:5]


	def get(self, request, **kwargs):
	
		latest_forecast = Forecast.objects.latest('timestamp')
		city= latest_forecast.city
		temperature_in_c = latest_forecast.temperature
		temperature_in_f = (latest_forecast.temperature * decimal.Decimal(1.8))+32
		description = latest_forecast.description.capitalize
		timestamp = "{t.year}/{t.month:02d}/{t.day:02d} - {t.hour:02d}:{t.minute:02d}:{t.second:02d}".format(t=latest_forecast.timestamp)
		#timestamp = "2018/12/11 - 12:12:00"
		#print "timestamp= "+ latest_forecast.timestamp
		return render(
			request,
			'polls/index.html',
			{
				'city': city,
				'temperature_in_c':temperature_in_c,
				'temperature_in_f':temperature_in_f,
				'description':description,
				'utc_update_time':timestamp
			})

class DetailView(generic.DetailView):
	model = Question
	template_name='polls/detail.html'

	

	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now() )

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'


def vote(request,question_id):
	question = get_object_or_404(Question,pk=question_id)
	
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])

	except(KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {'question':question,'error_message':"You didn't select a choice.",})
	else:
		selected_choice.votes +=1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))

def station(request):
	# https://impythonist.wordpress.com/2015/06/16/django-with-ajax-a-modern-client-server-communication-practise/
	# template = loader.get_template('polls/base.html')
	# context = {}
	


	if request.method == 'POST':
		if request.is_ajax():

			station = request.POST.get('stn') 
			state = request.POST.get('state')          
			data = {"stn":station , "state" : state}
			
			print data['stn']
			print state
			stn = Station("Station 1",station)
			stn.setup()
			
			if state == '0':
				print "state is 0"+state
				stn.off()
				sleep(1)
			else:
				print "state is 1"+state
				stn.on()
				sleep(1)	

			return JsonResponse(data)

	#return render(request,'polls/base.html')



scheduler = BackgroundScheduler()
scheduler.add_jobstore(DjangoJobStore(), "default")

def myjob():
	time.sleep(4)
	print("hello")


#scheduler.add_job(myjob,'cron',minute='*')
#scheduler.start()
jobs = scheduler.get_jobs()
print jobs

polls/templates/polls/base.html
{% load static %}

{% include 'polls/header.html' %}

{% include 'polls/nav.html' %}
<div class="container-fluid">
<div class="row">
	<div class="col"></div>
<div class="col">
 <form class="form-signin" method="POST">
    {% csrf_token %}
      <h2 class="form-signin-heading">Enter Details</h2>
     <label for="inputEmail" class="sr-only">Email address</label>
     <input type="email" id="inputEmail" class="form-control" placeholder="Email               address" required autofocus>
     <label for="inputPassword" class="sr-only">Password</label>
     <input type="password" id="inputPassword" class="form-control"  placeholder="Password" required>
     <button id="submit" class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
 </form>
</div>
<div class="col"></div>
</div>
</div>
{% include 'polls/footer2.html' %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %} " method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %} 
		<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}" />
		<label for="choice{{forloop.counter}}"> {{choice.choice_text}}</label><br/>
	{% endfor %}
	<input type="submit" value="Vote" />
</form>

polls/templates/polls/footer.html
{% load static %}

<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
 --><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.15/js/mdb.min.js"></script>


<!-- Propeller textfield js --> 
<script type="text/javascript" src="dist/js/propeller.min.js"></script>

<!-- Datepicker moment with locales -->
<script type="text/javascript" language="javascript" src="datetimepicker/js/moment-with-locales.js"></script>

<!-- Propeller Bootstrap datetimepicker -->
<script type="text/javascript" language="javascript" src="datetimepicker/js/bootstrap-datetimepicker.js"></script>

<script type="text/javascript" src={% static "/polls/wickedpicker/dist/wickedpicker.min.js" %}></script>

 <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>

<script>
  //for getting CSRF token
function getCookie(name){
  var cookieValue=null;
    if(document.cookie && document.cookie !=''){
      var cookies = document.cookie.split(';');
      for(var i=0;i<cookies.length;i++){
        var cookie = jQuery.trim(cookies[i]);

      
      if(cookie.substring(0,name.length+1)==(name+'=')){
        cookieValue=decodeURIComponent(cookie.substring(name.length+1));
        break;
      }}
    }
  return cookieValue;
}

//when submit is clicked
$("#submit").click(function(e){
  e.preventDefault();

  //prepare csrf token
  var csrftoken = getCookie('csrftoken');

  //collect data from fields
  var email = $('#inputEmail').val();
  var password = $('#inputPassword').val();

  $.ajax({
    //url: window.location.href,
    url: '{% url "polls:station" %}',
    type: 'POST',
    data:{csrfmiddlewaretoken: csrftoken,
      email:email,
      password:password
    },
    success: function(json){
      console.log(json);
      alert('Hi ' + json['email']+'!.'+' you have entered password '+json['password']);
      console.log("success");
    },
    error:function(xhr,errmsg,err){
      console.log("error is here: "+xhr.status + ": "+xhr.responseText);
    }
  });


});


var station1 = $("#stn1");
var station2 = $("#stn2");
var stn1Pin = "P8_8";
var stn2Pin = "P8_9";
var timeDelay = 3 * (1000);//time in seconds

station1.change(function(e){
  
  var switchStatus = false;
  var csrftoken = getCookie('csrftoken');

  if ($(this).is(':checked')) {
        switchStatus = $(this).is(':checked');
        ajaxCall(stn1Pin,1,e,csrftoken);

        //turn off after set amount of time
        setTimeout(function(){
        station1.bootstrapToggle('off');
        ajaxCall(stn1Pin,0,e,csrftoken)},timeDelay);
    }
    else {
        switchStatus = $(this).is(':checked');
        ajaxCall(stn1Pin,0,e,csrftoken);
    }


});


station2.change(function(e){
 var switchStatus = false;
 var csrftoken = getCookie('csrftoken');

if ($(this).is(':checked')) {
       
        switchStatus = $(this).is(':checked');
        ajaxCall(stn2Pin,1,e,csrftoken);

        //turn off after set amount of time
        setTimeout(function(){
        station2.bootstrapToggle('off');
        ajaxCall(stn2Pin,0,e,csrftoken)},timeDelay);
    }
    else {
      switchStatus = $(this).is(':checked');      
      ajaxCall(stn2Pin,0,e,csrftoken);
    }

});



function ajaxCall(stn, state,e,csrftoken){
 e.preventDefault();
    //var csrftoken = getCookie('csrftoken');
    $.ajax({
      url: '{% url "polls:station" %}',
      type:'POST',
      data:{csrfmiddlewaretoken : csrftoken,
        stn:stn,
        state:state
      },
      success: function(json){
        console.log(json);
        console.log("success");
      }
    });

}
// $('#input_starttime').pickatime({
//     // 12 or 24 hour
//     twelvehour: true,
// });
</script>

<script>
  
// Time picker only
  // $('#input_starttime').datetimepicker({
  //   format: 'LT'
  // });

  $('.timepicker').wickedpicker();

</script>

</body></html>

polls/templates/polls/footer2.html
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
 --><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

 <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>


   
<script>
  //for getting CSRF token
function getCookie(name){
  var cookieValue=null;
    if(document.cookie && document.cookie !=''){
      var cookies = document.cookie.split(';');
      for(var i=0;i<cookies.length;i++){
        var cookie = jQuery.trim(cookies[i]);

      
      if(cookie.substring(0,name.length+1)==(name+'=')){
        cookieValue=decodeURIComponent(cookie.substring(name.length+1));
        break;
      }}
    }
  return cookieValue;
}

//when submit is clicked
$("#submit").click(function(e){
  e.preventDefault();

  //prepare csrf token
  var csrftoken = getCookie('csrftoken');

  //collect data from fields
  var email = $('#inputEmail').val();
  var password = $('#inputPassword').val();

  $.ajax({
    //url: window.location.href,
    url: "{% url 'polls:home' %}",
    type: "POST",
    data:{csrfmiddlewaretoken: csrftoken,
      email:email,
      password:password
    },
    success: function(json){
      console.log(json);
      alert('Hi ' + json['email']+'!.'+' you have entered password '+json['password']);
      console.log("success");
    },
    error:function(xhr,errmsg,err){
      console.log(xhr.status + ": "+xhr.responseText);
    }
  });


});




</script>

</body></html>

polls/templates/polls/header.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

<title>Dashboard Template for Bootstrap</title>

<!-- <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'polls/dashboard.css'  %}" >
<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">

<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.15/css/mdb.min.css" rel="stylesheet">


<link href={% static "polls/wickedpicker/dist/wickedpicker.min.css"  %} rel="stylesheet">
</head>
  <body>

polls/templates/polls/index.html
{% load static %}

{% include 'polls/header.html' %}

{% include 'polls/nav.html' %}


<div class="container-fluid">
 <div class="row">

  {% include 'polls/left-nav.html' %}

  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Dashboard</h1>

      <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
          <button class="btn btn-sm btn-outline-secondary">Share</button>
          <button class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
        <button id="toggle-one" class="btn btn-sm btn-outline-secondary dropdown-toggle">
          <span data-feather="calendar"></span>
          This week
        </button>
      </div>
    </div>

    <div class="row"><!-- Weather data panel -->
      <div class="col">
        <div style="text-align: center;">
          <h5>Currently in</h5>
          <h3>{{city }}</h3>
          <h4>{{ temperature_in_f| floatformat }} F | {{ temperature_in_c }}</h4>
          <h4>{{ description }}</h4>
          <p><em>Last Updated {{ utc_update_time }} PST</em></p>
        </div>
      </div>
    </div><!-- #Weather data panel -->

    <div class="row"><!-- Station panel -->
      <div class="col">

        <div class="card" style="width: 25rem;">
          <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
          <div class="card-body">
            <form class="form-signin" method="POST" >
             {% csrf_token %}
             <div class="form-group" >
              <h5 class="card-title">Station 1</h5>
              <p class="card-text">werfpoj wer ipjg peork </p>
              <!-- <button type="button" id="stn1" class="btn btn-danger">Off</button> -->
              <input id="stn1" type="checkbox" data-toggle="toggle" data-onstyle="success" data-offstyle="danger">
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card" style="width: 25rem;">
        <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
        <div class="card-body">

         <form class="form-signin" method="POST" >
           {% csrf_token %}
           <div class="form-group">
            <h5 class="card-title">Station 2</h5>
            <p class="card-text">werfpoj wer ipjg peork </p>
            <!-- <button type="button" id="stn2" class="btn btn-danger">Off</button> -->
            <input id="stn2" type="checkbox" data-toggle="toggle" data-onstyle="success" data-offstyle="danger">
          </div>
        </form>
      </div>
    </div>
  </div>
</div><!--#station panel-->

<br>
<div class="card" >
  <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
  <div class="card-body">
    <h2 class="card-title">Schedule</h2>
    <div class="row">
      <div class='col-sm-6' id="start-time" >
        <div class="md-form">
          <input placeholder="Selected time" name="timepicker" type="text" id="input_starttime" class="timepicker">
          <label class="card-text" for="input_starttime">Start Time</label>
        </div>
      </div>
      <div class="card-text" class='col-sm-6' id="duration">
        Duration
      </div>
    </div>
    <div class="row">
      <div class='col-sm' id="day-of-week" >
        <div class='btn-group col-sm' data-toggle="buttons">
          <label class="btn btn-mdb-color form-check-label">
            <input class="form-check-input" type="checkbox" autocomplete="off">Sun
          </label>
          <label class="btn btn-mdb-color form-check-label">
            <input class="form-check-input" type="checkbox" autocomplete="off">Mon
          </label>
          <label class="btn btn-mdb-color form-check-label">
            <input class="form-check-input" type="checkbox" autocomplete="off">Tues
          </label>
          <label class="btn btn-mdb-color form-check-label">
            <input class="form-check-input" type="checkbox" autocomplete="off">Wed
          </label>
          <label class="btn btn-mdb-color form-check-label">
            <input class="form-check-input" type="checkbox" autocomplete="off">Thurs
          </label>
          <label class="btn btn-mdb-color form-check-label">
            <input class="form-check-input" type="checkbox" autocomplete="off">Fri
          </label>
          <label class="btn btn-mdb-color form-check-label">
            <input class="form-check-input" type="checkbox" autocomplete="off">Sat
          </label>
        </div>
      </div>
      </div>
    </div>
  </div>

  <br>
  <h2>Water Usage</h2>
  <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

  <h2>Poll Questions</h2>
  <div class="table-responsive">
    {% if latest_question_list %}
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>#</th>

        </tr>
      </thead>
      <tbody>
       {% for question in latest_question_list %}
       <tr>
         <td>
          <a href={% url 'polls:detail' question.id %}>{{question.question_text }}</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p>No polls are available.</p>
  {% endif %}
</div>

</main>

</div><!--#row-->

</div><!--#container-fluid-->





{% include 'polls/footer.html' %}

polls/templates/polls/left-nav.html
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file"></span>
                  Orders
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="shopping-cart"></span>
                  Products
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="users"></span>
                  Customers
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  Reports
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="layers"></span>
                  Integrations
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Saved reports</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Current month
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Last quarter
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Social engagement
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Year-end sale
                </a>
              </li>
            </ul>
          </div>
        </nav>

polls/templates/polls/nav.html
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Sprink Lord</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#">Sign out</a>
        </li>
      </ul>
    </nav>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote {{ choice.votes | pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

<a href="{% url 'polls:index'  %}">Home</a>